---
sudo: true
language: generic
services:
  - docker
install:
  - sudo apt update
  - sudo apt install -y coreutils
  - wget https://raw.githubusercontent.com/packethost/packet-images/master/tools/packet-save2image
  - chmod +x packet-save2image
  - sudo mv packet-save2image /usr/bin/packet-save2image
script:
  - git lfs pull
  - sudo ./build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/publish.sh
  on:
    branch: master
branches:
  only:
    - master
